### ISSUE TITLE
Onpress dont work will wrapped in containner

### ISSUE THREAD

**Issue by Yanaus** [LanarsInc/animated-bottom-navigation-bar-flutter#6] opened 2020-11-24 08:27 UTC
Hello,

Onpress function stop working when i wrapped the UnicornDialer button in a container 

Here is my code 

` @override
  Widget build(BuildContext context) {
    var childButtons = List<UnicornButton>();

    childButtons.add(UnicornButton(
        hasLabel: true,
        labelText: "Chii chii",
        currentButton: FloatingActionButton(
            heroTag: "airplane",
            backgroundColor: Colors.greenAccent,
            mini: true,
            onPressed: () {print('chii chii');},
            child: Icon(Icons.airplanemode_active))));

    childButtons.add(UnicornButton(
        hasLabel: true,
        labelText: "Choo choo",
        currentButton: FloatingActionButton(
            heroTag: "airplane",
            backgroundColor: Colors.greenAccent,
            mini: true,
            onPressed: () {print('choo choo');},
            child: Icon(Icons.airplanemode_active))));

    childButtons.add(UnicornButton(
        hasLabel: true,
        labelText: "Chaa chaa",
        currentButton: FloatingActionButton(
            heroTag: "directions",
            backgroundColor: Colors.blueAccent,
            mini: true,
            child: Icon(Icons.directions_car))));

    return Scaffold(
      
      floatingActionButton: Container(
        width: 100.0,
        height: 100.0,
        child: UnicornDialer(
            hasNotch: true,
            //hasBackground: false,
            backgroundColor: Color.fromRGBO(255, 255, 255, 0.0),
            parentButtonBackground: Colors.redAccent,
            orientation: UnicornOrientation.VERTICAL,
            parentButton: Icon(Icons.add),
            childButtons: childButtons),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: AnimatedBottomNavigationBar(
        gapLocation: GapLocation.center,
        notchSmoothness: NotchSmoothness.softEdge,
        icons: iconList,
        activeIndex: _currentIndex,
        inactiveColor: Colors.grey[800],
        onTap: (index) => onTabTapped(index),
      ),
      body: PageView(
        controller: _pageController,

        physics: NeverScrollableScrollPhysics(),  
        children: <Widget>[
          Explore(),
          StatesPage(),
          BookmarkPage(),
          ProfilePage(),
          MapSample()

        ],
      ),
    );
  }`

**Comment by vizhan-lanars** [comment] 2020-11-26 21:23
Hi
Could you be more specific, please?
As I understood, child buttons (UnicornButton) `onPressed` is not fired. I guess the issue is on the [unicorndial](https://pub.flutter-io.cn/packages/unicorndial) side. It's quite outdated.
I've found a couple of related issues [#13](https://github.com/tiagojencmartins/unicornspeeddial/issues/13) & [#46](https://github.com/tiagojencmartins/unicornspeeddial/issues/46). 
According to [answer](https://github.com/tiagojencmartins/unicornspeeddial/issues/13#issuecomment-508457854), try to give more space for UnicornDialer (e.g. **300.0**). See below:
```
  floatingActionButton: Container(
    width: 300.0,
    height: 300.0,
    child: UnicornDialer(
        hasNotch: true,
        //hasBackground: false,
        backgroundColor: Color.fromRGBO(255, 255, 255, 0.0),
        parentButtonBackground: Colors.redAccent,
        orientation: UnicornOrientation.VERTICAL,
        parentButton: Icon(Icons.add),
        childButtons: childButtons),
  ),
```
For now I'm going to close this issue.
Feel free to reopen it, if needed.

**Closed by vizhan-lanars** 2020-11-26 21:23 UTC
